[package]
name = "snake_dt"
version = "0.1.0"
edition = "2021"

[dependencies]
dfdx = "0.13.0"
decision_transformer_dfdx = {path = "../decision_transformer_dfdx"}
rand = "0.8.5"

[profile.release]
debug = true